name: Download translations

on:
  push:
    branches: [dev]
  schedule:
    - cron: '0 8 * * *'

jobs:
  download_translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download translations
        uses: crowdin/github-action@1.0.9
        env:
          GITHUB_TOKEN: ${{secrets.OTTO_THE_BOT_GH_TOKEN}}
          CROWDIN_PROJECT_ID: 342359
          INPUT_DEBUG_MODE: false
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          push_translations: false
          create_pull_request: false
          token: ${{secrets.WEB_CROWDIN_TOKEN}}
          source: '/src/i18n/en-US.json'
          translation: '/src/i18n/%locale%.json'
          base_path: '.'
          dryrun_action: true

      - name: Commit & push translations
        run: |
          git config --global user.email webapp+travis@wire.com
          git config --global user.name "Wire Travis CI"
          git status
          git diff-index --quiet HEAD || git commit -am 'chore: Update translations'
          git status
